const CATEGORIES = [
  'Identity & Citizenship',
  'Security & Verification',
  'Marriage & Family',
  'Business & Licensing',
  'Tax & Finance',
  'Transport & Vehicle',
  'Passport & Immigration',
  'Land & Property',
  'Education',
  'Health',
  'Employment',
  'Pension & Social Security',
  'Housing & Construction',
  'Agriculture & Livestock',
  'Justice & Legal',
  'Tourism & Culture',
];

const CATEGORY_COLORS = {
  'Identity & Citizenship': '#185FA5',
  'Security & Verification': '#7C3AED',
  'Marriage & Family': '#DB2777',
  'Business & Licensing': '#1D9E75',
  'Tax & Finance': '#D97706',
  'Transport & Vehicle': '#0891B2',
  'Passport & Immigration': '#4F46E5',
  'Land & Property': '#65A30D',
  'Education': '#2563EB',
  'Health': '#DC2626',
  'Employment': '#0D9488',
  'Pension & Social Security': '#9333EA',
  'Housing & Construction': '#CA8A04',
  'Agriculture & Livestock': '#16A34A',
  'Justice & Legal': '#64748B',
  'Tourism & Culture': '#EA580C',
};

const TOP_20_IDS = [9, 16, 17, 12, 3, 27, 28, 32, 24, 25, 26, 5, 11, 40, 1, 46, 48, 50, 44, 4];

const SERVICES = [
  { id: 1, name: 'CID Card Issuance', category: 'Identity & Citizenship', agency: 'DCRC, MoHA', url: 'https://www.citizenservices.gov.bt', description: 'Apply for or renew Citizen Identity Card. Required for most government services.' },
  { id: 2, name: 'Nationality Certificate', category: 'Identity & Citizenship', agency: 'DCRC, MoHA', url: 'https://www.citizenservices.gov.bt', description: 'Certificate confirming Bhutanese citizenship.' },
  { id: 3, name: 'Birth Registration', category: 'Identity & Citizenship', agency: 'DCRC, MoHA', url: 'https://www.citizenservices.gov.bt', description: 'Register births digitally via NDI App or ICS portal.' },
  { id: 4, name: 'Death Registration', category: 'Identity & Citizenship', agency: 'DCRC, MoHA', url: 'https://www.citizenservices.gov.bt', description: 'Register a death and obtain official death certificate.' },
  { id: 5, name: 'Household Information (Family Tree)', category: 'Identity & Citizenship', agency: 'DCRC, MoHA', url: 'https://www.citizenservices.gov.bt', description: 'Generate household/family tree using NDI App under the Family tab.' },
  { id: 6, name: 'Relationship Certificate', category: 'Identity & Citizenship', agency: 'DCRC, MoHA', url: 'https://www.citizenservices.gov.bt', description: 'Certifies family relationships for legal or official use.' },
  { id: 7, name: 'One and Same Person Certificate', category: 'Identity & Citizenship', agency: 'DCRC, MoHA', url: 'https://www.citizenservices.gov.bt', description: 'Certifies two or more names refer to the same individual.' },
  { id: 8, name: 'Lost Citizenship Document Reporting', category: 'Identity & Citizenship', agency: 'DCRC, MoHA', url: 'https://dcrc.moha.gov.bt', description: 'Report lost/found citizenship documents; track recovery.' },
  { id: 9, name: 'Security Clearance Certificate (NOC)', category: 'Security & Verification', agency: 'Royal Bhutan Police', url: 'https://scs.rbp.gov.bt', description: 'Apply for NOC via Bhutan NDI App for employment, travel, or business.' },
  { id: 10, name: 'Police Verification', category: 'Security & Verification', agency: 'Royal Bhutan Police', url: 'https://scs.rbp.gov.bt', description: 'Background check by RBP for employment or legal requirements.' },
  { id: 11, name: 'Audit Clearance', category: 'Security & Verification', agency: 'Royal Audit Authority', url: 'https://www.citizenservices.gov.bt', description: 'Required for civil service appointments and promotions.' },
  { id: 12, name: 'Marriage Registration', category: 'Marriage & Family', agency: 'DCRC, MoHA', url: 'https://www.citizenservices.gov.bt', description: 'Register marriage and obtain official marriage certificate.' },
  { id: 13, name: 'Divorce Services', category: 'Marriage & Family', agency: 'DCRC / Judiciary', url: 'https://www.citizenservices.gov.bt', description: 'Process divorce registration and related civil documentation.' },
  { id: 14, name: 'Child Registration', category: 'Marriage & Family', agency: 'DCRC, MoHA', url: 'https://www.citizenservices.gov.bt', description: 'Register a child in the civil registry following birth.' },
  { id: 15, name: 'Census Transfer', category: 'Marriage & Family', agency: 'DCRC, MoHA', url: 'https://www.citizenservices.gov.bt', description: 'Transfer census/household registration for resettlement or relocation.' },
  { id: 16, name: 'Business License — New', category: 'Business & Licensing', agency: 'MoEA / IBLS', url: 'https://ibls.systems.gov.bt', description: 'Apply for a new business license. Sole Proprietorship, Partnership, Company, or Other.' },
  { id: 17, name: 'Business License — Renewal', category: 'Business & Licensing', agency: 'MoEA / IBLS', url: 'https://ibls.systems.gov.bt', description: 'Renew existing business license annually.' },
  { id: 18, name: 'Business License — Amendment', category: 'Business & Licensing', agency: 'MoEA / IBLS', url: 'https://ibls.systems.gov.bt', description: 'Apply for changes/amendments to an existing license.' },
  { id: 19, name: 'Branch Opening / Business Extension', category: 'Business & Licensing', agency: 'MoEA / MoENR', url: 'https://www.moenr.gov.bt', description: 'Apply to open a branch office or extend business operations.' },
  { id: 20, name: 'Environment Clearance', category: 'Business & Licensing', agency: 'MoENR', url: 'https://www.moenr.gov.bt', description: 'Required for business or industrial projects with environmental impact.' },
  { id: 21, name: 'Import/Export Registration', category: 'Business & Licensing', agency: 'MoEA', url: 'https://www.citizenservices.gov.bt', description: 'Register as importer/exporter; cancel or update import house registration.' },
  { id: 22, name: 'Personal Income Tax Filing', category: 'Tax & Finance', agency: 'Dept. of Revenue & Customs', url: 'https://www.citizenservices.gov.bt', description: 'File personal income tax returns.' },
  { id: 23, name: 'Business Tax / CIT Filing', category: 'Tax & Finance', agency: 'Dept. of Revenue & Customs', url: 'https://www.citizenservices.gov.bt', description: 'File corporate income tax and business tax returns.' },
  { id: 24, name: 'Tax Clearance Certificate', category: 'Tax & Finance', agency: 'Dept. of Revenue & Customs', url: 'https://www.citizenservices.gov.bt', description: 'Required for tenders, travel, or employment.' },
  { id: 25, name: 'Land Tax Payment', category: 'Tax & Finance', agency: 'Dept. of Revenue & Customs', url: 'https://www.citizenservices.gov.bt', description: 'Pay land tax online.' },
  { id: 26, name: 'Property Tax Payment', category: 'Tax & Finance', agency: 'Dept. of Revenue & Customs', url: 'https://www.citizenservices.gov.bt', description: 'Pay property/municipal tax online.' },
  { id: 27, name: 'Driving License — New / Renewal', category: 'Transport & Vehicle', agency: 'RSTA, MoIT', url: 'https://www.citizenservices.gov.bt', description: 'Apply for new driving license or renew existing one.' },
  { id: 28, name: 'Vehicle Registration', category: 'Transport & Vehicle', agency: 'RSTA, MoIT', url: 'https://www.citizenservices.gov.bt', description: 'Register a new vehicle or update registration details.' },
  { id: 29, name: 'Vehicle Ownership Transfer', category: 'Transport & Vehicle', agency: 'RSTA, MoIT', url: 'https://www.citizenservices.gov.bt', description: 'Transfer vehicle ownership between individuals.' },
  { id: 30, name: 'Road Tax Payment', category: 'Transport & Vehicle', agency: 'RSTA, MoIT', url: 'https://www.citizenservices.gov.bt', description: 'Pay annual road tax for vehicles.' },
  { id: 31, name: 'Vehicle Fitness Certificate', category: 'Transport & Vehicle', agency: 'RSTA, MoIT', url: 'https://www.citizenservices.gov.bt', description: 'Obtain vehicle roadworthiness/fitness certification.' },
  { id: 32, name: 'Passport Application — New / Renewal', category: 'Passport & Immigration', agency: 'MFA (Passport Office)', url: 'https://www.mfa.gov.bt/passport-application/', description: 'Apply or renew Bhutanese passport online. Emergency in-person at Changangkha.' },
  { id: 33, name: 'Visa Application — Tourist', category: 'Passport & Immigration', agency: 'Dept. of Immigration, MoHA', url: 'https://permit.doi.gov.bt', description: 'Apply for tourist visas electronically.' },
  { id: 34, name: 'Non-Tourist Permit / Visa', category: 'Passport & Immigration', agency: 'Dept. of Immigration, MoHA', url: 'https://permit.doi.gov.bt', description: 'Work, study, or other non-tourist permits for foreign nationals.' },
  { id: 35, name: 'Route Permit', category: 'Passport & Immigration', agency: 'Dept. of Immigration, MoHA', url: 'https://permit.doi.gov.bt', description: 'Permits for travel to restricted areas. Fees payable online.' },
  { id: 36, name: 'Immigration Clearance', category: 'Passport & Immigration', agency: 'Dept. of Immigration, MoHA', url: 'https://permit.doi.gov.bt', description: 'Departure and arrival clearance through Bhutan ports of entry.' },
  { id: 37, name: 'Land Ownership Certificate', category: 'Land & Property', agency: 'Dept. of Survey & Land Records', url: 'https://www.citizenservices.gov.bt', description: 'Obtain official land ownership (Thram) certificate.' },
  { id: 38, name: 'Land Transfer', category: 'Land & Property', agency: 'Dept. of Survey & Land Records', url: 'https://www.citizenservices.gov.bt', description: 'Transfer land ownership between individuals.' },
  { id: 39, name: 'Property Registration', category: 'Land & Property', agency: 'Dept. of Survey & Land Records', url: 'https://www.citizenservices.gov.bt', description: 'Register property and obtain legal documentation of ownership.' },
  { id: 40, name: 'Scholarship Application', category: 'Education', agency: 'MoE / RCSC', url: 'https://www.citizenservices.gov.bt', description: 'Apply for government scholarships for higher education.' },
  { id: 41, name: 'Student Records / Transcripts', category: 'Education', agency: 'Ministry of Education', url: 'https://www.citizenservices.gov.bt', description: 'Access academic records, transcripts, and educational certificates.' },
  { id: 42, name: 'Examination Services', category: 'Education', agency: 'Bhutan Board of Examinations', url: 'https://www.citizenservices.gov.bt', description: 'Register for board exams, download admit cards, access results.' },
  { id: 43, name: 'Medical Certificate', category: 'Health', agency: 'MoH / Health Dept.', url: 'https://www.citizenservices.gov.bt', description: 'Official medical fitness certificate for employment or travel.' },
  { id: 44, name: 'Health Insurance Services', category: 'Health', agency: 'Dept. of Health / BNBL', url: 'https://www.citizenservices.gov.bt', description: 'Enrol in or update health insurance coverage.' },
  { id: 45, name: 'Hospital Services — Referral', category: 'Health', agency: 'MoH / JDWNRH', url: 'https://www.citizenservices.gov.bt', description: 'Access referral letters and hospital service bookings online.' },
  { id: 46, name: 'Employment Registration / Job Portal', category: 'Employment', agency: 'Dept. of Employment, MoLHR', url: 'https://www.citizenservices.gov.bt', description: 'Register for employment and access government job listings.' },
  { id: 47, name: 'Labour / Work Permit', category: 'Employment', agency: 'Dept. of Employment, MoLHR', url: 'https://www.citizenservices.gov.bt', description: 'Work permits for foreign nationals employed in Bhutan.' },
  { id: 48, name: 'Pension Claim', category: 'Pension & Social Security', agency: 'NPPF / DPAS', url: 'https://www.citizenservices.gov.bt', description: 'Submit and track pension claims upon retirement from civil service.' },
  { id: 49, name: 'Retirement Benefits', category: 'Pension & Social Security', agency: 'NPPF / DPAS', url: 'https://www.citizenservices.gov.bt', description: 'Access and manage retirement and provident fund benefits.' },
  { id: 50, name: 'Building Approval / Construction Permit', category: 'Housing & Construction', agency: 'Thromde / MoIT / CDB', url: 'https://www.citizenservices.gov.bt/cdb/', description: 'Apply for building plan approval and construction permits.' },
  { id: 51, name: 'Livestock Registration', category: 'Agriculture & Livestock', agency: 'Dept. of Livestock, MoAF', url: 'https://www.citizenservices.gov.bt', description: 'Register livestock and obtain animal health certificates.' },
  { id: 52, name: 'Agriculture / Farm Permits', category: 'Agriculture & Livestock', agency: 'Dept. of Agriculture, MoAF', url: 'https://www.citizenservices.gov.bt', description: 'Apply for farm subsidies, seeds, and agriculture-related permits.' },
  { id: 53, name: 'Court Services / Legal Certificates', category: 'Justice & Legal', agency: 'Judiciary of Bhutan', url: 'https://www.citizenservices.gov.bt', description: 'Obtain certified court documents and legal certificates.' },
  { id: 54, name: 'Grievance Services', category: 'Justice & Legal', agency: 'Anti-Corruption Commission', url: 'https://www.citizenservices.gov.bt', description: 'File complaints and track grievances through official channels.' },
  { id: 55, name: 'Tourism Permits', category: 'Tourism & Culture', agency: 'Dept. of Tourism', url: 'https://www.citizenservices.gov.bt', description: 'Apply for tourism-related permits and protected area access.' },
  { id: 56, name: 'Cultural Affairs Services', category: 'Tourism & Culture', agency: 'Dept. of Culture, MoHCA', url: 'https://www.citizenservices.gov.bt', description: 'Services related to cultural preservation, heritage, and events.' },
];

SERVICES.forEach((service) => {
  const rankIndex = TOP_20_IDS.indexOf(service.id);
  service.topRank = rankIndex >= 0 ? rankIndex + 1 : null;
});
